"""Pydantic schemas for API requests and responses."""
from typing import Optional, Dict, Any, List
from pydantic import BaseModel, Field


class HealthResponse(BaseModel):
    """Health check response."""
    status: str = Field(..., description="Pipeline status: initializing, ready, or failed")
    ready: bool = Field(..., description="True if pipeline is ready to handle requests")
    error: Optional[str] = Field(None, description="Error message if status is failed")
    detector_device: Optional[str] = Field(None, description="Device used for detection")
    translator_device: Optional[str] = Field(None, description="Device used for translation")
    gpu_device: Optional[str] = Field(None, description="GPU device name if CUDA is used")
    system_memory_gb: Optional[float] = Field(None, description="Total system RAM in GB")
    system_memory_used_gb: Optional[float] = Field(None, description="Used system RAM in GB")
    gpu_total_memory_gb: Optional[float] = Field(None, description="Total GPU VRAM in GB")


class TranslateRequest(BaseModel):
    """Translation request payload."""
    imagePath: str = Field(..., description="Absolute path to the image file to translate")
    postId: Optional[str] = Field("0", description="Optional post/metadata ID")
    targetLang: Optional[str] = Field("ENG", description="Target translation language (e.g., ENG, VIE)")
    
    # Optional device settings
    device: Optional[str] = Field(None, description="Torch device for detection & OCR (cpu, cuda, mps, auto)")
    llmDevice: Optional[str] = Field(None, description="Execution device for LLM (cpu, cuda, mps, auto)")
    modelPath: Optional[str] = Field(None, description="Custom path to GGUF model")
    translator: Optional[str] = Field(None, description="Translator backend: 'llm' or 'deep-translator'")
    
    # LLM tuning parameters
    llmGpuLayers: Optional[int] = Field(None, description="Number of GPU layers for LLM")
    llmContextSize: Optional[int] = Field(None, description="LLM context size (512-8192)")
    llmMaxTokens: Optional[int] = Field(None, description="Maximum tokens generated by LLM")
    llmBatchSize: Optional[int] = Field(None, description="LLM batch size")
    llmUbatchSize: Optional[int] = Field(None, description="LLM micro-batch size")
    llmThreads: Optional[int] = Field(None, description="LLM CPU threads")
    llmForceMmq: Optional[str] = Field(None, description="Force GGML CUDA MMQ (yes, no, auto)")
    llmForceCublas: Optional[str] = Field(None, description="Force GGML CUDA CUBLAS (yes, no, auto)")
    llmForceGpu: Optional[bool] = Field(None, description="Force LLM to use GPU")
    llmAutoDowngrade: Optional[bool] = Field(None, description="Auto-downgrade LLM on VRAM contention")
    llmContentionThreshold: Optional[int] = Field(None, description="VRAM threshold for LLM contention (GB)")
    
    # Hugging Face model options
    hfRepo: Optional[str] = Field(None, description="Hugging Face repository ID for GGUF model")
    hfModelFile: Optional[str] = Field(None, description="GGUF model filename in HF repository")
    
    # Detection parameters
    detectionSize: Optional[int] = Field(None, description="Detection input size")
    textThreshold: Optional[float] = Field(None, description="Detection text threshold")
    boxThreshold: Optional[float] = Field(None, description="Detection box threshold")
    unclipRatio: Optional[float] = Field(None, description="Detection unclip ratio")
    detInvert: Optional[bool] = Field(None, description="Invert detection input")
    detGammaCorrect: Optional[bool] = Field(None, description="Apply gamma correction to detection")
    detRotate: Optional[bool] = Field(None, description="Enable detection rotation")
    detAutoRotate: Optional[bool] = Field(None, description="Enable detection auto-rotation")
    
    # Misc
    verbose: Optional[bool] = Field(None, description="Enable verbose logging")


class TextOverlay(BaseModel):
    """Translated text overlay region."""
    id: str
    xywh: Dict[str, float]
    polygon: List[Dict[str, float]]
    sourceText: str
    translatedText: str
    confidence: float
    sourceLang: str


class TranslationTimings(BaseModel):
    """Timing breakdown for the translation pipeline."""
    totalMs: int
    imageLoadMs: int
    imageDecodeMs: int
    detectMs: int
    ocrMs: int
    mergeMs: int
    translateMs: int
    normalizeMs: int
    detectorDevice: str
    translatorDevice: str
    detectedTextlines: int
    recognizedTextlines: int
    mergedRegions: int


class TranslateResponse(BaseModel):
    """Translation response with results and timings."""
    postId: str
    imagePath: str
    originalSize: Dict[str, int]
    translator: str
    elapsedMs: int
    timings: TranslationTimings
    overlays: List[TextOverlay]


class ErrorResponse(BaseModel):
    """Error response body."""
    error: str = Field(..., description="Error message")
    errorCode: str = Field(..., description="Error code (e.g., INVALID_INPUT, MODEL_NOT_READY)")
    status: str = Field("error", description="Status indicator")
    retryable: Optional[bool] = Field(None, description="Whether the request can be retried")
